### ISSUE TITLE
DRK Problems - Lv70/80/90

### ISSUE THREAD

**Issue by Akechi-kun** [xanunderscore/ffxiv_bossmod#1]
1. AOE combo does not do the full AOE rotation. It's merely doing 1-2 then using Bloodspiller & Edge of Shadow, instead of Quietus & Flood of Shadow. This is for all Lv70/80/90 content. 
2. If you use AOE combo and it activates Delirium, all 3 stacks are wasted as AOE combo will not consume any & just keep using Bloodspiller ONLY when you have enough gauge, completely ignoring the stacks. 
3. Reprisal, Arm's Length, & Oblation are used as a target action rather than a self action (Self-action Reprisal is seen on GNB & WAR, but not DRK)

Currently, the AOE combo is the only thing that needs some work. 
ST combo works just fine and hasn't given me any issues in any Lv70/80/90 content.

**Comment by xanunderscore** [comment]
> 3. Reprisal, Arm's Length, & Oblation are used as a target action rather than a self action (Self-action Reprisal is seen on GNB & WAR, but not DRK)

sorry i'm not following, are you referring to the cdplan? i checked WARActions and GNBActions and they have no special logic for arm's length at all. Reprisal also seems to work correctly for me when planned.

**Comment by xanunderscore** [comment]
> > 3. Reprisal, Arm's Length, & Oblation are used as a target action rather than a self action (Self-action Reprisal is seen on GNB & WAR, but not DRK)
> 
> sorry i'm not following, are you referring to the cdplan? i checked WARActions and GNBActions and they have no special logic for arm's length at all. Reprisal also seems to work correctly for me when planned.

clarified on discord, original comment is talking about the green bar in the cdplanner, which is missing for oblation and reprisal. the green bar represents EffectDuration and i just forgot to set it for those skills, it has no effect on the behavior of the rotation
