### ISSUE TITLE
[BUG] L100 Reaper: rotation cringes if opener isn't correct

### ISSUE THREAD

**Issue by Richieer** [xanunderscore/ffxiv_bossmod#4]
**Bug description**
If during opener the reaper uses harpe prepull but doesnt get in range in time, to start the rotation so the rotation uses harvest moon as well
![image](https://github.com/user-attachments/assets/afe2bb62-c558-47e9-9310-a149b47ce74d)
The rotation gets stuck doing basic combo
![image](https://github.com/user-attachments/assets/0fc81203-a398-4595-9bff-73b90e9a6a85)
Or every even minute double shroud starts like this with a hard clipped shadow of death, instead of the usual double shadow of death
![image](https://github.com/user-attachments/assets/3d4feaec-ddc8-4e87-92a5-f8bf77b02a2a)

**Replay info** - only one choice is needed
- [ ] I have a(n anonymized) video recording of this interaction
- [ ] I have a replay file and I will DM it to you upon request (or just post it here if I don't care about privacy)
- [ ] I can attach my `/xllog` from when the issue occurred
- [x] I have a screenshot of or link to xivanalysis

**Comment by xanunderscore** [comment]
1. should be easy to fix. i completely forgot that harpe and harvest moon even give gauge
2. i can repro the early arcane circle, but not the regular GCDs after soul slice, it uses enshroud normally. please provide a replay
3. i think should be fixed by the fix to 1

**Comment by xanunderscore** [comment]
try with 469852f
